dist: focal

addons:
  apt:
    packages:
      - build-essential
      - python3-dev

cache:
    pip: true

services: postgresql

language: "python"
python:
  - "3.8"
  - "3.9"

install:
  - pip install -r dev-requirements.txt

before_script:
  - psql -c "ALTER USER postgres PASSWORD 'postgres';" -U postgres
  - python3 setup.py build_ext --inplace
  - python3 setup_database.py

script:
  - pytest --cov=app tests

after_success:
  - codecov -t 12cf570a-7fe2-41f1-8229-579cd9085f8d